sudo: false

language: go

go:
  - 1.5

install: 
  - ln -s $HOME/gopath/src/github.com/hashicorp/terraform $HOME/gopath/src/github.com/odise/terraform
  - make updatedeps

script:
  - make test
  - make dev

branches:
  only:
    - travis

matrix:
  fast_finish: true
  allow_failures:
    - go: tip
