sudo: false

language: go

go:
  - 1.5

install:
  - mkdir -p $HOME/gopath/src/github.com/hashicorp/
  - ln -s $HOME/gopath/src/github.com/odise/terraform $HOME/gopath/src/github.com/hashicorp/terraform
  - make updatedeps

script:
  - make test
  - make dev
  - make testacc TEST=./builtin/providers/aws TESTARGS='-run=OpsworksApplication'

branches:
  only:
    - travis

matrix:
  fast_finish: true
  allow_failures:
    - go: tip
